- 
  name: 'Set up Local Server configs'
  hosts: in-house
  become: yes
  tasks:
    - name: Edit hostname
      lineinfile:
        path: /etc/hostname
        regexp: "centos*" 
        line: "{{ hostname }}.{{ansible_host}}"
        state: present
        backup: yes
    - name: Edit hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: "127.0.0.1 localhost {{ hostname }}.{{ansible_host}}"
        state: present
        backup: yes
    - name: "Reboot host and wait for it to restart"
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
- 
  name: 'Set up WebAPP Server'
  hosts: web-servers
  become: yes
  tasks:
    - name: 'Install LAMP dependencies'
      vars:
        packages:
          - firewalld
          - httpd
          - php
          - git
      yum: 
        name: '{{ packages }}'
        state: present
    - name: 'Enable firewalld'
      service:
        name: firewalld
        state: reloaded
        enabled: True
    - name: 'Permit traffic in default zone for http service'
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: 'Reload firewalld'
      command: firewall-cmd --reload
    - name: 'Set up httpd - Change DirectoryIndex'
      shell: sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf
    - name: 'Set up httpd - Update Listening IP'
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'Listen '
        line: 'Listen {{ ansible_host }}:80'
    - name: 'Reload service httpd, in all cases'
      systemd:
        name: httpd
        state: restarted
    - name: 'Set up git - Clone the repo'
      git:
        repo: '{{ gitrepo }}'
        dest: /var/www/html/